### ISSUE TITLE
Note the turns at which each tier of animals is enabled

### ISSUE THREAD

**Issue by aboucher51** [bencoveney/super-auto-pets-db#10]
maybe add the notation to the headers on the left, something like

🎲 Tier 2 - enabled on turn 3

**Comment by bencoveney** [comment]
That's a great idea. I've just pushed a change that enables this on the homepage.

I think it could also be useful to display similar information for each pet - and also somewhere describe how levelling up a pet gives you early access to higher tier pets. I'll leave this open until I've done that.

Thanks for contributing.

**Comment by bencoveney** [comment]
More detailed information has been added to pet pages about when they become available through levelling up etc - as part of #15
