### ISSUE TITLE
Suggestion: make ability effects consistent

### ISSUE THREAD

**Issue by WolfDWyc** [bencoveney/super-auto-pets-db#19]
For example, the Ox has an array `effects` attribute for it's abilities, while other pets have a a single `effect` attribute.
For consistency and parsing purposes, I suggest an array `effects` attribute for all pets that would only contain a single element if there's only one effect.

**Comment by WolfDWyc** [comment]
Sorry, my mistake - I didn't read the JSON correctly.

**Comment by bencoveney** [comment]
I have held off on documenting the API shape, as it was changing a lot as I worked through the different pets. Looks like it might be time to have a go at that soon. There's a note to do this on  #17.

**Comment by WolfDWyc** [comment]
No, this actually wasn't an inconsistency and the Ox has an "effect" that has "effects" between it which is a good way of doing it, I just missed that on my first read.
