### ISSUE TITLE
Missing information in Goat and Sauropod abilities

### ISSUE THREAD

**Issue by WolfDWyc** [bencoveney/super-auto-pets-db#21]
The Goat and Sauropod have missing information in their abilities (and in those abilities' description) about the max triggers of the ability per turn.

**Comment by bencoveney** [comment]
I've pushed a change that adds an optional `maxTriggers` property to abilities. I have applied this to the sauropod, and also the Gorilla's Coconut Shield ability.

Do you know the limits for how many times each can be triggered? For Sauropod I found on the discord that the limits are 3/6/9 per turn. Is it the same for the Goat?

**Comment by WolfDWyc** [comment]
> Do you know the limits for how many times each can be triggered, and whether they depend on the level of the Goat? For Sauropod I found on the discord that the limits are 3/6/9 per turn. Is it the same for the Goat?

I managed to find this video where someone levels up a goat (and then immediately sells it, but oh well), it should be timestamped to that moment: https://youtu.be/dVqk8KkrD3Q?t=1068

I think it's safe to assume that if level 1 is 3 per turn and level 2 is 6 per turn than level 3 is 9 per turn.

Also, it's kind of funny how it's so rare we both didn't actually know what it does.

**Comment by bencoveney** [comment]
Nice find! I've added that update for the goat.
