### ISSUE TITLE
Missing ability for butterfly

### ISSUE THREAD

**Issue by WolfDWyc** [bencoveney/super-auto-pets-db#23]
The butterfly currently has no abilities listed, it's ability should be of trigger type `Summoned` (with triggeredBy.kind `Self`) and a and have the following effect for all levels:
```json
       "effect": {
          "kind": "TransferStats",
          "copyAttack": true,
          "copyHealth": true,
          "from": {
            "kind": "StrongestFriend",
          },
          "to": {
            "kind": "Self"
          }
       }
```
I think this JSON is correct, but please double check it anyway.

**Comment by bencoveney** [comment]
Fixed, thanks!
