### ISSUE TITLE
0.16 Update Changes

### ISSUE THREAD

**Issue by Undadadolmen** [bencoveney/super-auto-pets-db#35]
- Changed Whale to 3/8.
- Changed Swan to 1/3.
- Changed T-Rex ability not to affect itself.
- Changed Dragon ability not to affect itself.
- Changed Monkey ability to give +2/+3.
- Changed Peacock to 2/5 and ability to Hurt: Gain 50% Attack (with charges)
- Changed Snail ability to give +1/+1.
- Changed Rat ability to summon Dirty Rat up front.
- Changed Duck to 1/3.

**Comment by bencoveney** [comment]
Resolved by #36
